version: "3"
services:
  app:
    build:
      context: .
    environment:
     - HOST_IP=datadog
  datadog:
    image: datadog/agent:7.35.2
    links:
     - app
    environment:
     - DD_API_KEY=<placeholder>
     - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT=0.0.0.0:4318
     - DD_APM_ENABLED=true
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
